### ISSUE TITLE
Display matches improvement

### ISSUE THREAD

**Issue by hoodoos** [nagaozen/gedit-plugin-autocomplete#10]
Would be great if matches can be sorted in the way they were met, i mean they should come in this order:
1) the ones from the document currently open
2) then the rest

Would be great to have some kind of scope and first display matches from closes scope, scope can be defined as { }, so basicly you gotta build scopes from current position and display matches that way, then in the order I suggested earlier. I guess all languages have some kind of scope definition, like \t for python e.g.

Maybe someday I'll get to implement it here. And it would be a great chance to know python better :)

**Comment by nagaozen** [comment]
I think this is the way it works now in 0.11.0
