### ISSUE TITLE
How to switch back to tab?

### ISSUE THREAD

**Issue by paulchubatyy** [nagaozen/gedit-plugin-autocomplete#11]
Is there any way to switch back to tab completition?

**Comment by nagaozen** [comment]
In the main version? It should not be done... because tab is used for snippets. But you can just open the source and change the key binding from <return> to <tab>.

**Comment by paulchubatyy** [comment]
well thanks. I'm using autocomplete much more often than snippets. Also it's more logical to me to trigger snippets via enter and leave the autocomplete via tab. IMHO, surely. Thanks for the input.

**Comment by paulchubatyy** [comment]
Could you please provide the link to the source code where should I change the trigger?

**Comment by nagaozen** [comment]
You will be glad to know that i've rebuilt autocompletion plugin to work integrated with GTKSourceCompletion framework and it now works with both <Return> and <Tab>.
