### ISSUE TITLE
Unable to switch between word alternatives in a special case

### ISSUE THREAD

**Issue by vincent-petithory** [nagaozen/gedit-plugin-autocomplete#2]
Steps to reproduce : 
1. Open a few documents
2. Move an opened document in another window (Documents -> Move in another window)
3. Only in that moved document, the completion is fully functional but you cannot switch between the word alternatives.

Possible reasons : activate()/deactivate() handlers are not called by gedit

**Comment by vincent-petithory** [comment]
Workaround : close and open again the document

**Comment by nagaozen** [comment]
Should be fixed in 0.11.0
