### ISSUE TITLE
Provide a base word completion list depending of the language of the document

### ISSUE THREAD

**Issue by vincent-petithory** [nagaozen/gedit-plugin-autocomplete#4]
Actually, a global list of completion words is available. The feature can be enhanced by proposing that global list, plus a list specific for the language of the document.

As an extra feature, all keywords of a language may be included by default to its word completion list

**Comment by vincent-petithory** [comment]
The implementation has begun.
Languages available through gtksourceview 2 are found.
A simple ui (TreeView with ListStore) displays the languages and a text view is attached so we can add words for the selected language.
Logic still need to be done.

**Comment by vincent-petithory** [comment]
Using a gedit.Document with correct highlighting instead of a TextView.
Everything is in a beta state and should be tested before being validated.

**Comment by nagaozen** [comment]
I used Xmas and New Year to recode the plugin. HAPPY 2010!!! All features are now available through some json configs. We need to push more libraries into this project.
