### ISSUE TITLE
where do i add autocomplete docs?

### ISSUE THREAD

**Issue by dantrevino** [nagaozen/gedit-plugin-autocomplete#6]
this takes  a json doc, but can i add an arbitrary json doc to use?  where do i add it?

**Comment by nagaozen** [comment]
Yes... you can add an arbitrary json for any language you want. You should place it at: ~/.gnome2/gedit/plugins/autocomplete/lib/<gtk_language_name>.json

**Comment by dantrevino** [comment]
what is the implication of <gtk_language_name> is there a finite set of these defined somewhere?  Or can I add my own completely made up api?
