### ISSUE TITLE
Hitting the up arrow when the popup shows up, will ignore the beginning of the completed word

### ISSUE THREAD

**Issue by ghost** [nagaozen/gedit-plugin-autocomplete#8]
Hi,

When I start to write a word to complete, the popup shows up. If I press the up arrow, to get to the bottom of the list, first it does not select the last element (I have to press it twice for this), then, more importantly, when I press Enter, the entire selected word is written out, instead of taking into account the beginning of the word I started writing and only complete it.

If I first press the bottom arrow, and then twice the top arrow, everything will work alright.

I'm using Gedit 2.30.3, and Autocomplete trunk from today (last change August 04, 2010).

Thanks in advance,

Bye.

**Comment by hoodoos** [comment]
I prove this for AutoComplete 0.10.1 and gedit 2.30.3

**Comment by nagaozen** [comment]
should be fixed in 0.11.0
